### ISSUE TITLE
Wrong app state in State tutorial ?

### ISSUE THREAD

**Issue by gphilipp** [awkay/om-remote-tutorial#13]
Isn't [this line](https://github.com/awkay/om-tutorial/blob/master/src/tutorial/om_tutorial/E_State_Reads_and_Parsing.cljs#L362) supposed to read: 

```
(def app-state (atom {:a 1 :user {:user/name \"Sam\"} :c 99}))
```

instead ?

**Comment by awkay** [comment]
Nope, the code is live. The point is that the state can be flat, and the parser can end up generating the desired structure...The UI query and app state are decoupled by read,

**Comment by gphilipp** [comment]
Ok thanks !
