### ISSUE TITLE
How to handle websocket push events in om.next

### ISSUE THREAD

**Issue by favetelinguis** [awkay/om-remote-tutorial#22]
From your turtorial my guess it that the way to handle websockets push messages is to use `om/transact!` in the websocket eventhandler?

However in the following youtube video:
https://www.youtube.com/watch?v=IlNrmKYA7Ig

There is a comment about handling websockets push messages but im not understanding what that comment actually is.

**Comment by artemyarulin** [comment]
Not the author, but after discussion with David on slack I've implemented it like that:
1. Add `:merge-tree merger` to the reconciler
2. `merger` defined as `(defn merger [state new-item]` which should merge new data to the state
3. Call `om/merge!` from the outside (webSocker handler, etc.) like

```
(.setTimeout js/window #(om/merge! rec {:new "data"}) 3000)
```

**Comment by favetelinguis** [comment]
Nice, thanks! Might be a good input for the turtorial...

**Comment by awkay** [comment]
Steps 1/2 are optional (though the default merge-tree is just merge). merge! is the standard way to put new stuff into your app database. merge! accepts a query, so if you have new data and a query (for normalization), then you can simply merge it in. You might want/need to call om/force-root-render! to rerender everything.
