### ISSUE TITLE
Error in browser console - Maximum call stack size exceeded core.cljs:4629

### ISSUE THREAD

**Issue by viktor-evdokimov** [awkay/om-remote-tutorial#6]
On every reload I am getting the following error in console

```
Uncaught Range Error: Maximum call stack size exceeded cljs$core$tail_off @ core.cljs:4629
cljs.core.PersistentVector.cljs$core$ICollection$_conj$arity$2 @ core.cljs:4770
cljs$core$_conj @ core.cljs:470cljs.core.conj.cljs$core$IFn$_invoke$arity$2 @ core.cljs:1572
(anonymous function) @ core.cljs:9424
(anonymous function) @ core.cljs:4869
(anonymous function) @ core.cljs:4869
cljs.core.PersistentVector.cljs$core$IReduce$_reduce$arity$3 @ core.cljs:4873
cljs.core.reduce.cljs$core$IFn$_invoke$arity$3 @ core.cljs:2197
cljs$core$group_by @ core.cljs:9421
utils.cljs?rel=1449115188238:38 
Figwheel: trying to open cljs reload socket
```

**Comment by pfernandez** [comment]
I was getting this error today too, although nothing was affected adversely (that I could see).

**Comment by awkay** [comment]
The demo application needs Om bug fixes that are not released yet. The recursive query in Person causes an infinite recursion. David has merged my fix for it, so if you use checkouts and the tip of master it should work fine. If not, just sit tight...beta Om coming soon.

Or are you running just the tutorial?

**Comment by awkay** [comment]
Yeah, that was it...turns out one of the tutorial files was including parts of the app. I removed the requires and that seems to eliminate it in the tutorial itself.
